module usl.usl_def;

import usl.usl_type;

USTR USL_TOP_LINE = "// BEGIN USERLAND KERNEL SOURCE AUTOGENERATED CODE
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

#define i64 long long
#define u64 unsigned long long
#define i32 int
#define u32 unsigned int
#define i16 short
#define byte char

#define UVersion char*
#define UError char*
#define UStr char*

#define Malloc(bytes) malloc(bytes)
#define Realloc(bytes) realloc(bytes)
#define Free(bytes) free(bytes)
#define CAlloc(bytes) calloc(bytes)

extern int Print (UStr);
extern char* Concatenate (char*, char*);

// END USERLAND KERNEL SOURCE AUTOGENERATED CODE
";
